events {
    worker_connections 1024;
}

http {
    upstream analysis {
        server lrlre-analysis:8007;
    }
    
    upstream visual {
        server lrlre-visual:8009;
    }
    
    upstream ultimate {
        server lrlre-ultimate:8013;
    }
    
    server {
        listen 80;
        server_name localhost;
        
        location /analysis {
            proxy_pass http://analysis;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /visual {
            proxy_pass http://visual;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /ultimate {
            proxy_pass http://ultimate;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
